server:
  port: 6303

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  application:
    name: ScannerProcessor
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---
spring:
  profiles: default,dev
  datasource:
    url: jdbc:h2:~/scanner-processor
    #username: sa
    #password:
    #driver-class-name: com.h2.com
  jpa:
    show-sql: false

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost:3306/processormanager
    username: root
    password: Scanner_p4ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto : update

