server:
  port: 6303

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  application:
    name: ScannerProcessor
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

